env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
builds:
  - binary: sn-cli
    id: sn-cli
    main: cmd/sncli/main.go
    env:
    - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}'
    goos:
        - freebsd
        - windows
        - linux
      goarch:
        - amd64
        - '386'
        - arm
        - arm64
      ignore:
        - goos: darwin
          goarch: '386'
        - goarch: arm
        - goarch: '386'
        - goos: windows
          goarch: amd64
  - binary: sn-cli
    id: sn-cli-macos
    goos:
    - darwin
    goarch:
    - amd64
    hooks:
      post: gon gon.json

archives:
  - id: default
    wrap_in_directory: true



// "darwin/amd64 linux/amd64 linux/arm linux/arm64 windows/amd64 netbsd/amd64 openbsd/amd64 freebsd/amd64"
